import os
import shutil
import subprocess

def main():
    print("Starting ComfyUI-Custom-Batchbox secure build process...")
    
    # 1. Compile all Python files
    print("Compiling Python source files to .pyd...")
    try:
        subprocess.run(["python", "setup_build.py"], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Compilation failed: {e}")
        return
        
    # 2. Setup dist directory framework
    dist_dir = os.path.join("dist", "ComfyUI-Custom-Batchbox")
    if os.path.exists("dist"):
        shutil.rmtree("dist")
    os.makedirs(dist_dir)
    
    # 3. Copy required files to dist
    print("Copying compiled binaries and assets to dist/...")
    
    for root, dirs, files in os.walk("."):
        # Exclude directories we don't want to copy
        dirs[:] = [d for d in dirs if d not in ["venv", ".worktrees", "tests", "dist", ".git", "__pycache__", ".agents", "docs"]]
            
        for file in files:
            # We want to copy .pyd files, regular web assets, and __init__.py
            is_pyd = file.endswith(".pyd") or file.endswith(".so")
            is_asset = file.endswith(".js") or file.endswith(".css") or file.endswith(".html") or file.endswith(".json") or file.endswith(".yaml")
            is_doc = file in ["README.md", "LICENSE"]
            is_init = file == "__init__.py" and root == "."
            is_static = file.endswith(".png") or file.endswith(".jpg")
            
            if is_pyd or is_asset or is_doc or is_init or is_static:
                # Exclude secrets/api_config logic from being packaged as static files
                if file == "secrets.yaml" or file == "api_config.yaml" or file.endswith(".enc"):
                    continue
                    
                src_path = os.path.join(root, file)
                rel_path = os.path.relpath(src_path, ".")
                dest_path = os.path.join(dist_dir, rel_path)
                
                os.makedirs(os.path.dirname(dest_path), exist_ok=True)
                shutil.copy2(src_path, dest_path)
                
    # 4. Cleanup local .pyd/c files generated by cythonize to keep working dir clean
    print("Cleaning up intermediate compilation files...")
    for root, dirs, files in os.walk("."):
        if "venv" in root or ".worktrees" in root or "dist" in root:
            continue
        for file in files:
            if file.endswith(".pyd") or file.endswith(".c") or file.endswith(".so"):
                try:
                    os.remove(os.path.join(root, file))
                except OSError:
                    pass
                    
    print(f"Build complete! Packaged extension is ready in: {dist_dir}")

if __name__ == "__main__":
    main()
